site_name: NovaIT Products Documentation
# добавляет линк тег в голову страниц и берет путь для serve
site_url: https://netheria.github.io/novadocs/
# добавляет мета тег в хеадер с информацией
site_description: NovaIt documentation site_description
# добавляет мета тег в хеадер с информацией
site_author: NovaIt
# copyright: инфа добавляется в документацию темой

#Repository
# repo_url: делает линки на каждой странице
# remote_branch: gh-pages (ветка, куда будет комитить с помощью gh-deploy GitHub Pages)
# remote_name: origin (куда будет пушить с помощью gh-deploy)

# Станицы документации
nav:
    - Features:
        - Nova.ChatsConnector:
            - Nova.BotConnector: components/novabotconnectornotices.md
            - Nova.BotFlow: components/novabotflow.md
            - Nova.ChatProxy:
                - Cisco.ECE: components/novachatproxyciscoece.md
                - Cisco.UCCX: components/novachatproxyciscouccx.md
                - Genesys.PureCloud: components/novachatproxygenesyspurecloud.md
                - Genesys.PureConnect.ICWS: components/novachatproxygenesyspureconnecticws.md
                - Genesys.PureEngage.GMS.ChatAPIv2: components/novachatproxygenesyspureengagegmschatapiv2.md
                - NovaIT.Chat24: components/novachatproxynovaitchat24.md
            - Nova.ChatRouter:
                - Dialogflow: components/novachatrouterdialogflow.md
                - Omilia: components/novachatrouteromilia.md
            - Nova.WebChat: components/novawebchat.md
    - Release Notes:     
        - Nova.BotConnector: components/novabotconnector.md
        - Nova.BotFlow: components/novabotflow.md
        - Nova.ChatProxy: components/novachatproxy.md
        - Nova.ChatProxy.Cisco.ECE: components/novachatproxyciscoece.md
        - Nova.ChatProxy.Cisco.UCCX: components/novachatproxyciscouccx.md
        - Nova.ChatProxy.Genesys.PureCloud: components/novachatproxygenesyspurecloud.md
        - Nova.ChatProxy.Genesys.PureConnect.ICWS: components/novachatproxygenesyspureconnecticws.md
        - Nova.ChatProxy.Genesys.PureEngage.GMS.ChatAPIv2: components/novachatproxygenesyspureengagegmschatapiv2.md
        - Nova.ChatProxy.NovaIT.Chat24: components/novachatproxynovaitchat24.md
        - Nova.ChatRouter.Dialogflow: components/novachatrouterdialogflow.md
        - Nova.ChatRouter.Omilia: components/novachatrouteromilia.md
        - Nova.WebChat: components/novawebchat.md

theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.instant
  font:
    text: Roboto
    code: Roboto Mono
#  favicon: assets/logo.png
#  icon:
#    logo: logo
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: assets/icon.png
  favicon: assets/favicon.png
  icon:
    logo: assets/logo.png

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

extra:
  homepage: https://netheria.github.io/novadocs/components/
 
use_directory_urls: false