site_name: NovaIT Products Documentation
# добавляет линк тег в голову страниц и берет путь для serve
site_url: https://netheria.github.io/novadocs/
# добавляет мета тег в хеадер с информацией
site_description: NovaIt documentation about products
# добавляет мета тег в хеадер с информацией
site_author: NovaIT
# copyright: Owned by NovaIT

#Repository
# repo_url: делает линки на каждой странице
# remote_branch: gh-pages (ветка, куда будет комитить с помощью gh-deploy GitHub Pages)
# remote_name: origin (куда будет пушить с помощью gh-deploy)

# Станицы документации
nav:
    - components\botconnector\text.md
    - Features:
        - Nova.ChatsConnector:
            - Nova.BotConnector: components/novabotconnectornotices.md
            - Nova.BotFlow: components/novabotflownotices.md
            - Nova.ChatProxy:
                - Cisco.ECE: components/novachatproxyciscoecenotices.md
                - Cisco.UCCX: components/novachatproxyciscouccxnotices.md
                - Genesys.PureCloud: components/novachatproxygenesyspurecloudnotices.md
                - Genesys.PureConnect.ICWS: components/novachatproxygenesyspureconnecticwsnotices.md
                - Genesys.PureEngage.GMS.ChatAPIv2: components/novachatproxygenesyspureengagegmschatapiv2notices.md
                - NovaIT.Chat24: components/novachatproxynovaitchat24notices.md
            - Nova.ChatRouter:
                - Dialogflow: components/novachatrouterdialogflownotices.md
                - Omilia: components/novachatrouteromilianotices.md
            - Nova.WebChat: components/novawebchatnotices.md
    - Release Notes:       
        - Nova.ChatsConnector:
            - Nova.BotConnector: components/novabotconnector.md
            - Nova.BotFlow: components/novabotflow.md
            - Nova.ChatProxy:
                - Cisco.ECE: components/novachatproxyciscoece.md
                - Cisco.UCCX: components/novachatproxyciscouccx.md
                - Genesys.PureCloud: components/novachatproxygenesyspurecloud.md
                - Genesys.PureConnect.ICWS: components/novachatproxygenesyspureconnecticws.md
                - Genesys.PureEngage.GMS.ChatAPIv2: components/novachatproxygenesyspureengagegmschatapiv2.md
                - NovaIT.Chat24: components/novachatproxynovaitchat24.md
            - Nova.ChatRouter:
                - Dialogflow: components/novachatrouterdialogflow.md
                - Omilia: components/novachatrouteromilia.md
            - Nova.WebChat: components/novawebchat.md

theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.instant
  font:
    text: Roboto
    code: Roboto Mono
#  favicon: assets/logo.png
#  icon:
#    logo: icon.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  logo: components/assets/icon.png
  favicon: components/assets/favicon.png
  icon:
    logo: components/assets/icon.png

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

extra:
  homepage: https://netheria.github.io/novadocs/components/
  generator: false
 
use_directory_urls: false